name: Terraform Apply
on:
  workflow_dispatch:
    inputs:
      project_id:
        description: "GCP project ID"
        required: true
      region:
        description: "Region"
        required: true
        default: us-central1

permissions:
  contents: read
  id-token: write   # for Workload Identity Federation

env:
  TF_IN_AUTOMATION: true
  TF_INPUT: false
  TF_CLI_ARGS_init: -input=false
  TF_CLI_ARGS_apply: -auto-approve -lock-timeout=5m

jobs:
  apply:
    runs-on: ubuntu-latest
    concurrency:
      group: tf-${{ github.ref }}-apply
      cancel-in-progress: false

    steps:
      - uses: actions/checkout@v4

      # Auth to Google Cloud (WIF). If using a key instead, swap this step per notes below.
      - name: Auth (WIF)
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WIF_PROVIDER }}
          service_account: ${{ secrets.GCP_WIF_SA }}

      - uses: google-github-actions/setup-gcloud@v2
      - uses: hashicorp/setup-terraform@v3

      # Create an explicit backend config on the fly (adjust bucket/prefix!)
      - name: Backend config
        working-directory: terraform
        run: |
          cat > backend.hcl <<'HCL'
          bucket = "YOUR_TF_STATE_BUCKET"
          prefix = "terraform/state/dev"
          HCL

      - name: Init
        working-directory: terraform
        run: terraform init -backend-config=backend.hcl

      - name: fmt & validate
        working-directory: terraform
        run: |
          terraform fmt -check
          terraform validate

      - name: Plan
        working-directory: terraform
        run: |
          terraform plan \
            -var="project_id=${{ inputs.project_id }}" \
            -var="region=${{ inputs.region }}" \
            -out=tfplan.bin
          terraform show -no-color tfplan.bin > tfplan.txt

      - name: Apply
        working-directory: terraform
        run: terraform apply -input=false tfplan.bin

      - name: Upload plan (artifact)
        uses: actions/upload-artifact@v4
        with:
          name: tfplan.txt
          path: terraform/tfplan.txt

      # Safety: if apply fails, try to destroy to avoid charges
      - name: Destroy on failure
        if: failure()
        working-directory: terraform
        run: |
          terraform destroy \
            -var="project_id=${{ inputs.project_id }}" \
            -var="region=${{ inputs.region }}" \
            -auto-approve
