name: Terraform CI

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  packages: read

jobs:
  terraform:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/hooubis/terraform-env:1.0.0   # Use your custom Docker image
      credentials:
        username: hooubis
        password: ${{ secrets.ghcr-io-schhin }}

    #   - uses: actions/checkout@v4
    #   - uses: docker/login-action@v3
    #     with:
    #       registry: ghcr.io
    #       username:

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Verify Terraform version
      run: terraform --version

    # - name: Initialize Terraform
    #   run: terraform init 
    #   working-directory: ./terraform/envs/dev

    # - name: Validate Terraform configuration
    #   run: terraform validate
    #   working-directory: ./terraform/envs/dev   

