name: Terraform CI

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/YOUR_USERNAME/YOUR_IMAGE_NAME:latest
      options: --user root

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Verify Terraform version
      run: terraform --version

    # Add your Terraform init/plan/apply steps here
