name: Terraform CI

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/hooubis/terraform-env:latest   # Use your custom Docker image
      options: --user ${{ github.ACTOR }}  # Run as non-root user for improved security and to follow best practices, preventing permission issues inside the container
    env:
      TERRAFORM_IMAGE: ghcr.io/hooubis/terraform-env:latest
      ACTOR: ${{ github.ACTOR }}
    # steps:
    #   - uses: actions/checkout@v4
    #   - uses: docker/login-action@v3
    #     with:
    #       registry: ghcr.io
    #       username: ${{ github.ACTOR }}
    #       password: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Verify Terraform version
      run: terraform --version

    # - name: Initialize Terraform
    #   run: terraform init 
    #   working-directory: ./terraform/envs/dev

    # - name: Validate Terraform configuration
    #   run: terraform validate
    #   working-directory: ./terraform/envs/dev   

