name: Terraform CI

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/schhin/terraform-env:latest # Use your custom Docker image
      options: --user root

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Verify Terraform version
      run: terraform --version

    # - name: Initialize Terraform
    #   run: terraform init 
    #   working-directory: ./terraform/envs/dev

    # - name: Validate Terraform configuration
    #   run: terraform validate
    #   working-directory: ./terraform/envs/dev   

