name: TF Apply (ephemeral GCS state)

on:
  workflow_dispatch: {}

permissions:
  contents: read
  id-token: write         # required for OIDC to GCP
  packages: read          # only needed if you pull a private GHCR image

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  # Core config comes from repo secrets (set these in Settings → Secrets and variables → Actions)
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GCP_REGION:     ${{ secrets.GCP_REGION }}
  GCP_ZONE:       ${{ secrets.GCP_ZONE }}
  ALLOWED_CIDR:   ${{ secrets.ALLOWED_CIDR }}                    # e.g., 203.0.113.45/32
  GCP_STATE_BUCKET_LOCATION: ${{ secrets.GCP_STATE_BUCKET_LOCATION || 'us-central1' }}

  # Terraform automation ergonomics
  TF_IN_AUTOMATION: true
  TF_INPUT: false
  TF_CLI_ARGS_apply: -auto-approve -lock-timeout=5m
  TF_CLI_ARGS_destroy: -auto-approve -lock-timeout=5m

jobs:
  apply:
    runs-on: ubuntu-latest
    environment: gcpa-variables

    steps:
      - uses: actions/checkout@v4

      # Authenticate to GCP via OIDC (Workload Identity Federation)
      - name: Auth to Google Cloud (WIF)
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WIF_PROVIDER }}
          service_account:           ${{ secrets.GCP_WIF_SA }}

      - uses: google-github-actions/setup-gcloud@v2
      - uses: hashicorp/setup-terraform@v3

      # Clear any impersonation leftover from base images/env to avoid conflicts
      - name: Clear gcloud impersonation
        shell: bash
        run: |
          gcloud config unset auth/impersonate_service_account || true
          unset CLOUDSDK_AUTH_IMPERSONATE_SERVICE_ACCOUNT || true
          unset GOOGLE_IMPERSONATE_SERVICE_ACCOUNT || true    # <-- add this
          gcloud config get-value auth/impersonate_service_account || true
          gcloud auth list

      # Create a temporary GCS bucket for Terraform state (ephemeral backend)
      - name: Create temp state bucket
        id: mkbucket
        working-directory: terraform
        shell: bash
        env:
          STATE_LOC: ${{ secrets.GCP_STATE_BUCKET_LOCATION || 'us-central1' }}
          GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
        run: |
          set -euo pipefail
          BUCKET="tfstate-${GITHUB_RUN_ID}-${GITHUB_RUN_ATTEMPT}-$$"
          BUCKET="${BUCKET,,}"
          echo "STATE_BUCKET=$BUCKET" >> "$GITHUB_ENV"

          # Create bucket (no gcloud config mutation; pass project inline)
          gcloud storage buckets create "gs://${BUCKET}" \
            --project="${GCP_PROJECT_ID}" \
            --location="${STATE_LOC}"

          # Set 2-day lifecycle so leftovers self-clean
          cat > lifecycle.json <<'JSON'
          {"rule":[{"action":{"type":"Delete"},"condition":{"age":2}}]}
          JSON
          gcloud storage buckets update "gs://${BUCKET}" \
            --project="${GCP_PROJECT_ID}" \
            --lifecycle-file=lifecycle.json

          # Inject ephemeral backend config
          cat > backend.hcl <<HCL
          bucket = "${BUCKET}"
          prefix = "state"
          HCL


      - name: Terraform init
        working-directory: terraform
        run: terraform init -reconfigure -backend-config=backend.hcl

      - name: Format & Validate
        working-directory: terraform
        run: |
          terraform fmt -recursive
          terraform validate

      - name: Plan
        id: plan
        working-directory: terraform
        shell: bash
        run: |
          CIDR="${{ secrets.ALLOWED_CIDR }}"
          terraform plan \
            -var="project_id=${GCP_PROJECT_ID}" \
            -var="region=${GCP_REGION}" \
            -var="zone=${GCP_ZONE}" \
            -var="allowed_cidr=${CIDR}" \
            -out=tfplan.bin
          terraform show -no-color tfplan.bin > tfplan.txt

      - name: Apply
        working-directory: terraform
        run: terraform apply -input=false tfplan.bin

      # Save state as artifact (belt & suspenders)
      - name: Snapshot state (artifact)
        if: always()
        working-directory: terraform
        shell: bash
        run: |
          mkdir -p tfstate
          gsutil cp "gs://${STATE_BUCKET}/state/default.tfstate" tfstate/terraform.tfstate || true
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: tfstate-${{ github.run_id }}-${{ github.run_attempt }}
          path: terraform/tfstate/

      # Auto-destroy on failure to avoid resource leaks
      - name: Destroy on failure
        if: failure()
        working-directory: terraform
        shell: bash
        run: |
          CIDR="${{ secrets.ALLOWED_CIDR }}"
          terraform destroy \
            -var="project_id=${GCP_PROJECT_ID}" \
            -var="region=${GCP_REGION}" \
            -var="zone=${GCP_ZONE}" \
            -var="allowed_cidr=${CIDR}"

      # Always delete the temporary state bucket
      - name: Delete temp bucket
        if: always()
        shell: bash
        run: |
          if [[ -n "${STATE_BUCKET:-}" ]]; then
            gsutil -m rm -r "gs://${STATE_BUCKET}" || true
          fi

      # Upload human-readable plan for auditing
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: tfplan-${{ github.run_id }}-${{ github.run_attempt }}
          path: terraform/tfplan.txt
