name: tf-destroy-from-artifact

on:
  workflow_dispatch:
    inputs:
      run_id:
        description: "Workflow run ID that produced the state artifact (numeric)"
        required: true
      artifact_name:
        description: "Artifact name (e.g. tfstate-<run_id>-<attempt>)"
        required: true

permissions:
  id-token: write     # for google-github-actions/auth (WIF)
  contents: read      # checkout
  actions: read       # allow download-artifact by run-id

env:
  # Passed as job env so we don’t keep repeating
  GCP_PROJECT_ID:       ${{ secrets.GCP_PROJECT_ID }}
  GCP_REGION:           ${{ secrets.GCP_REGION }}
  GCP_ZONE:             ${{ secrets.GCP_ZONE }}
  ALLOWED_CIDR:         ${{ secrets.ALLOWED_CIDR }}
  TF_WORKDIR:           terraform/envs/dev
  TF_IN_AUTOMATION:     "true"
  TF_INPUT:             "false"
  TF_CLI_ARGS_destroy:  "-auto-approve -lock-timeout=5m"

jobs:
  destroy:
    runs-on: ubuntu-latest
    environment: gcpa-variables
    
    steps:
      - uses: actions/checkout@v4

      # OIDC -> short-lived ADC for Google provider
      - name: Auth to Google Cloud (WIF)
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WIF_PROVIDER }}
          service_account:           ${{ secrets.GCP_WIF_SA }}
          create_credentials_file:   true
          export_environment_variables: true

      - uses: google-github-actions/setup-gcloud@v2
      - uses: hashicorp/setup-terraform@v3

      # ensure no stray impersonation set in gcloud
      - name: Clear gcloud impersonation
        shell: bash
        run: |
          gcloud config unset auth/impersonate_service_account || true
          unset CLOUDSDK_AUTH_IMPERSONATE_SERVICE_ACCOUNT || true
          gcloud auth list


      # download the state artifact created by the apply job
      - name: Download state artifact
        uses: actions/download-artifact@v5
        with:
          name:   ${{ inputs.artifact_name }} # e.g. tfstate-17592363753-2
          run-id: ${{ inputs.run_id }}         # e.g. 17592363753
          path:   ${{ github.repository }}/${{ env.TF_WORKDIR }}


      # Terraform runs from the env directory which is configured for local backend
      - name: Terraform init (local backend)
        working-directory: ${{ env.TF_WORKDIR }}
        run: terraform init -reconfigure

      # Destroy using the downloaded local state
      - name: Terraform destroy
        working-directory: ${{ env.TF_WORKDIR }}
        shell: bash
        run: |
          terraform destroy \
            -var="project_id=${GCP_PROJECT_ID}" \
            -var="region=${GCP_REGION}" \
            -var="zone=${GCP_ZONE}" \
            -var="allowed_cidr=${ALLOWED_CIDR}"
